title: Player Guide
description: A guide for new and returning players to SentienceMUD
theme: just-the-docs

url: https://playerguide.sentiencemud.net

color_scheme: dark

aux_links:
  Main Site: https://sentiencemud.net
  Discord: https://discord.gg/22UVsSnChW
  
nav_external_links:
 - title: "Immortal Guide"
   url: https://immguide.sentiencemud.net
   hide-icon: true
 - title: "Builder Guide"
   url: https://olc.sentiencemud.net
   hide-icon: true

callouts:
  warning:
    title: Warning
    color: red
  notice:
    title: Notice
    color: yellow
  info:
    title: Note
    color: purple

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"