title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://playerguide.sentiencemud.net

color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
 - title: "Immortal Guide"
   url: https://immguide.sentiencemud.net
   hide-icon: true
 - title: "Builder Guide"
   url: https://olc.sentiencemud.net
   hide-icon: true